---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Manage SSH keys for monitoring and site synchronization
  include: ssh.yml

- name: Manage Check_MK sites
  include: site.yml
  with_items: '{{ checkmk_server__sites }}'
  loop_control:
    loop_var: site_item

- name: Monitoring site user authentication
  include: users.yml
  with_items: '{{ checkmk_server__sites }}'
  loop_control:
    loop_var: site_item
  tags:
    - 'role::checkmk_server:multisite'
    - 'role::checkmk_server:users'

- name: Trigger reload/restart handlers
  meta: flush_handlers

- name: Login on distributed sites
  include: login.yml
  when: (checkmk_server__sites | length) > 1
  tags:
    - 'role::checkmk_server:login'

- name: Manage WATO and monitoring rules
  include: wato.yml
  when: (checkmk_server__sites | length) > 0

- name: Upload configuration to slave sites
  include: sync.yml
  when: ('multisite_replication' in site_item) and
        (site_item.multisite_replication == 'slave')
  with_items: '{{ checkmk_server__sites }}'
  loop_control:
    loop_var: site_item
  tags:
    - role::checkmk_server:rules
    - role::checkmk_server:multisite
