---
# IMPORTANT:
# These tasks are run for each Check_MK site defined on the local
# server. This means they can run multiple times per server. The
# site configuration is available through `site_item`.

- name: Read SSH public key
  command: 'cat {{ site_item.home }}/.ssh/id_rsa.pub'
  register: checkmk_server__register_ssh_public_key
  changed_when: False

- name: Show SSH public key of site '{{ site_item.name }}'
  debug:
    var: checkmk_server__register_ssh_public_key.stdout
    verbosity: 1

- name: Save Check_MK server local facts
  template:
    src: 'etc/ansible/facts.d/checkmk_server.fact.j2'
    dest: '/etc/ansible/facts.d/checkmk_server.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
